import { StyleSheet } from 'react-native';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingTop: 35,
  },
  introTitle: {
    fontSize: 23,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    pointerEvents: 'none',
    marginTop: 50,
  },
  inputsContainer: {
    width: '100%',
    paddingHorizontal: 35,
  },
  button: {
    backgroundColor: '#544E61',
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    borderRadius: 5,
    marginBottom: 10,
    height: 50,
  },
  buttonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  orText: {
    lineHeight: 20,
    textAlign: 'center',
    paddingVertical: 1,
    marginVertical: 4,
    color: 'gray',
    marginVertical: 4,
    paddingHorizontal: 10,
    position: 'relative',
    backgroundColor: '#FFF',
    width: 50,
    alignSelf: 'center',
  },
  orBorder: {
    backgroundColor: '#d7d6d6',
    height: 1,
    width: '100%',
    position: 'relative',
    bottom: 14,
    zIndex: -1,
  },
  registerButton: {
    marginTop: 0,
    backgroundColor: '#76b698',
    marginTop: 10,
    flexDirection: 'row',
  },
  registerButtonText: {
    color: '#FFF',
    marginRight: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorMessageContainer: {
    backgroundColor: '#FFF5F5',
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingVertical: 10,
    marginTop: 15,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#fc8181',
  },
  errorMessage: {
    fontSize: 16,
    color: '#C53030',
  },
  section: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  paragraph: {
    fontSize: 15,
  },
  checkbox: {
    margin: 8,
    marginLeft: 0,
  },
});
